name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: getpkgs
      run: sudo apt install xcb cmake gcc libgtk-3-dev ninja-build libgdk-pixbuf2.0-dev libgtk2.0-dev libglib2.0-dev
    - name: configure
      run: make clear
    - name: make
      run: make release
